export const icons = {
  coding: "/images/icons/coding.svg",

  arrowUp: "/images/icons/arrow-up.svg",
  arrowDown: "/images/icons/arrow-down.svg",
  arrowLeft: "/images/icons/arrow-left.svg",
  arrowRight: "/images/icons/arrow-right.svg",
  cross_rounded: "/images/icons/cross_rounded.svg",
  home: "/images/icons/home.svg",
  chevron_right: "/images/icons/chevron_right.svg",
  chevron_down: "/images/icons/chevron_down.svg",
  chevron_left: "/images/icons/chevron_left.svg",
  chevron_up: "/images/icons/chevron_up.svg",
  sound: "/images/icons/sound.svg",
  copy: "/images/icons/copy.svg",
  external_link: "/images/icons/external_link.svg",
  settings: "/images/icons/settings.svg",
  search: "/images/icons/search.svg",
  check_circle: "/images/icons/check_circle.svg",
  edit: "/images/icons/edit.svg",
  records: "/images/icons/records.svg",
  delete: "/images/icons/delete.svg",
  arrow_right_long: "/images/icons/arrow_right_long.svg",
  file_image: "/images/icons/file_image.svg",
  plus: "/images/icons/plus.svg",
  exchange: "/images/icons/exchange.svg",
  refresh: "/images/icons/refresh.svg",
};
